schema: 'http://localhost:4000/graphql'
documents: packages/web/src/graphql/**/**/*.graphql
extensions:
  codegen:
    generates:
      packages/web/src/generated/graphql.ts:
        plugins:
          - typescript
          - typescript-operations
          - typescript-react-apollo
    overwrite: true
