name: Deploy Frontend Prod
on: 
  push:
    branches: [ prod ]

jobs:
  Deploy-Frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - run: yarn install  
      - run: npm run build:web
      - run: yarn workspace @abb/web style
      - run: curl -X POST -d {} ${{ secrets.BUILD_HOOK }}
