name: Deploy Server
on: 
  push:
    branches: [ staging ]

jobs:
  Deploy-Server:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
      FRONTEND_HOST: http://localhost:3000


    steps:
      - uses: actions/checkout@v2 
      - run: echo Install  
      - run: ls  
      - run: yarn install  
      - run: yarn build  
      - run: echo  ${{ env.FRONTEND_HOST }}
 