name: Deploy Server
on: 
  push:
    branches: [ staging ]

jobs:
  Deploy-Server:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
      FRONTEND_HOST: http://localhost:3000


    steps:
      - uses: actions/checkout@v2 
      - run: echo Install  
      - run: ls  
      - run: yarn install  
      - run: yarn build  
      - run: echo  ${{ env.FRONTEND_HOST }}
      - run: docker build -t alisalim17/abb:latest .  
      - run: docker push alisalim17/abb:latest
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker pull alisalim17/abb:latest 
            docker tag alisalim17/abb:latest dokku/api:latest 
            dokku tags:deploy api latest
 