name: Deploy Frontend
on: 
  push:
    branches: [ staging ]

jobs:
  Deploy-Frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - name: Build the site & install dependicies
        run: |
          yarn install 
          npm run build:web
          yarn build:netlify

      - name: Build with Netlify
        uses: jsmrcaga/action-netlify-deploy@master
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.SITE_ID }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          NETLIFY_DEPLOY_MESSAGE: "Prod deploy v${{ github.ref }}"
          NETLIFY_DEPLOY_TO_PROD: false
          netlify-config-path: ./netlify.toml
          build_command: netlify deploy --build
          build_directory: packages/web/out
          functions-dir: packages/web/out_functions
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true



