name: Deploy Frontend
on: 
  push:
    branches: [ staging ]

jobs:
  Deploy-Frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - name: Build the site & install dependicies
        run: |
          yarn install 
          npm run build:web
          npm install -g netlify-cli
          netlify link  --auth=${{ secrets.NETLIFY_TOKEN }} --id ${{ secrets.SITE_ID }}
          netlify login --auth=${{ secrets.NETLIFY_TOKEN }}
          netlify build

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: 'packages/web/out'
          functions-dir: 'packages/web/out_functions'
          production-branch: master
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.SITE_ID }}
        timeout-minutes: 1



          