name: Deploy Frontend
on: 
  push:
    branches: [ staging ]

jobs:
  Deploy-Frontend:
    runs-on: ubuntu-latest
    steps:
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: yarn install
      - run: npm run build
  
