name: Deploy Frontend
on: 
  push:
    branches: [ staging ]

jobs:
  Deploy-Frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - run: yarn install  
      - run: npm run build
      
      - name: Deploy to Netlify
        uses: jsmrcaga/action-netlify-deploy@v1.1.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.SITE_ID }}
          build_command: netlify build
          NETLIFY_DEPLOY_TO_PROD: true
          script: |
            echo hello
            echo hello2