name: Deploy Server
on: 
  push:
    branches: [ prod ]

jobs:
  Deploy-Server:
    runs-on: ubuntu-latest
    steps:
      # - run: yarn build:server
      # - run: docker build -t alisalim17/abb:latest .  
      # - run: docker push alisalim17/abb:latest
  
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          key: ${{ secrets.KEY }}
          script: whoami 
 
      # - run: docker pull alisalim17/abb:latest && docker tag alisalim17/abb:latest dokku/api:latest && dokku tags:deploy api latest
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
